### ISSUE TITLE
Failing to collect the Application information

### ISSUE THREAD

**Issue by djuneja-uptycs** [microsoftgraph/msgraph-beta-sdk-go#259] opened 2023-03-30 10:18 UTC
### Description:
Our use case requires us to collect all of the App Registration information from the Azure Active Directory. We are employing the `msgraph-beta-sdk-go` for collecting the Application Registrations.
Sample Code:

```
// List of required fields, generally we fetch almost all of the information by providing
// attribute name in the below list
requiredFields = []string{
		"appId",
		"appRoles",
		"certification"
	}

func (c *clientImpl) ListApplications(ctx context.Context, maxResult int32) ([]beta_models.Applicationable, error) {
	ctx = azure.CtxWithOperationName(ctx, "ListApplications")
	// Only request specific properties
	query := applications.ApplicationsRequestBuilderGetQueryParameters{
		Select: requiredFields,
		Expand: []string{"owners"},
		Top:    &maxResult,
	}

	result, err := c.betaClient.Applications().Get(ctx, &applications.ApplicationsRequestBuilderGetRequestConfiguration{
		QueryParameters: &query,
	})
	if err != nil {
		return nil, err
	}

	appList := make([]beta_models.Applicationable, 0)

	pageIterator, err := msgraphcore.NewPageIterator(result, c.adapter, beta_models.CreateApplicationCollectionResponseFromDiscriminatorValue)
	if err != nil {
		return nil, err
	}

	err = pageIterator.Iterate(ctx, func(pageItem interface{}) bool {
		app := pageItem.(beta_models.Applicationable)
		appList = append(appList, app)
		return true
	})
	if err != nil {
		return nil, err
	}

	return appList, nil
}
```

We are getting an error:
```
targetType is not supported
```

This error is coming from kiota-serialization as far as I can tell. Surprisingly there was a similar bug we filed in the `msgraph-sdk-go` sometime back, where we were failing to collect the AAD User related information.
Bug Link: https://github.com/microsoftgraph/msgraph-sdk-go/issues/410

Although the above issue was fixed in the MSGraph SDK release `v0.56`

`msgraph-beta-sdk-go` version: `v0.54.0`
`kiota-serialization-json-go` version: `v0.8.2`

**Comment by djuneja-uptycs** [comment] 2023-03-31 09:48
@rkodev any update on this?

**Comment by rkodev** [comment] 2023-03-31 10:46
Hi @djuneja-uptycs, this issue is as a result of serialization of uuid's that was resolved in `v0.56` and above.  Kindly update your dependencies and test if the issue is still persistent.

**Comment by djuneja-uptycs** [comment] 2023-03-31 12:06
@rkodev @baywet 
```
github.com/microsoft/kiota-authentication-azure-go v0.6.0
	github.com/microsoft/kiota-http-go v0.16.0
	github.com/microsoft/kiota-serialization-json-go v0.8.2
	github.com/microsoftgraph/msgraph-beta-sdk-go v0.54.0
	github.com/microsoftgraph/msgraph-sdk-go v0.56.0
	github.com/microsoftgraph/msgraph-sdk-go-core v0.34.1
```

We have the updated msgraph-sdk (`v0.56`). The fix was delivered in `kiota-serialization-json-go`, which was again a upgraded with the msgraph-sdk (related dependency).

**Comment by djuneja-uptycs** [comment] 2023-04-01 10:09
@rkodev these are the versions that we are already having, and we are still seeing the issue, I posted the above set of information to let you know that we already did the upgrade long back (right after the release).

**Comment by djuneja-uptycs** [comment] 2023-04-03 06:40
Hi @rkodev @baywet, as per my last comment, we already have the updated dependencies. And besides we are using the `msgraph-beta-sdk-go` (not the `msgraph-sdk-go`) for this task. Could this have any impact? Let me know if you have any more pointers for me.

**Comment by djuneja-uptycs** [comment] 2023-04-05 08:30
@rkodev @baywet, sorry for bugging you again, but do we have any update on this?

**Comment by rkodev** [comment] 2023-04-05 13:42
@djuneja-uptycs Please update `kiota-serialization-json-go` to v0.9.1 and share the error message you receive.

**Comment by rkodev** [comment] 2023-04-11 09:19
Hi @djuneja-uptycs do you have any update on this issue?

**Comment by djuneja-uptycs** [comment] 2023-04-12 05:24
@rkodev thanks for checking up on this. We are still working on this, unfortunately we are not able to re-create the same scenario which was causing the error. We have upgraded the `kiota-serialization-json-go` lib to suggested version and trying to perform our test runs on that. I will update as soon as we have the results with us.

**Closed** 2023-04-19 19:01 UTC
Labels: question, Needs: author feedback, Status: no recent activity

**Comment by djuneja-uptycs** [comment] 2023-04-29 09:50
@rkodev apologies, we were finally able to reproduce the scenario and I am glad that the upgrade you suggested worked for us. We are not seeing this issue anymore with version `0.9.1`. Thanks a lot for providing support on this.
